name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Qt
      uses: jurplel/install-qt-action@v2.8.0
    - name: configure
      run: qmake
    - name: make
      run: make

